"""B18.4 citation existence and metadata verification regressions."""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from httpx import AsyncClient

from app.services.reference_service import reference_service

MATCHED = {
    "bibtex": "@article{canonical, title={Attention Is All You Need}}",
    "cite_key": "canonical",
    "title": "Attention Is All You Need",
    "authors": "Vaswani, Ashish and Shazeer, Noam",
    "year": 2017,
    "cached": False,
}


class TestBibTeXMetadataParser:
    def test_nested_braces_and_multiple_entries(self) -> None:
        parsed = reference_service.parse_bibtex_entries(
            """@article{first,
              title = {{An {Important} Result}},
              author = {Lovelace, Ada and Hopper, Grace},
              year = {1843}, doi = {10.1000/example}
            }
            @misc(second, title="Another Result", eprint={1706.03762})"""
        )
        assert [entry["cite_key"] for entry in parsed] == ["first", "second"]
        assert parsed[0]["title"] == "{An {Important} Result}"
        assert parsed[0]["doi"] == "10.1000/example"
        assert parsed[1]["eprint"] == "1706.03762"

    def test_rejects_unterminated_entry(self) -> None:
        with pytest.raises(ValueError, match="unterminated"):
            reference_service.parse_bibtex_entries("@article{broken, title={Oops}")

    def test_rejects_missing_key(self) -> None:
        with pytest.raises(ValueError, match="cite key"):
            reference_service.parse_bibtex_entries("@article{, title={Oops}}")

    def test_rejects_more_than_twenty_entries(self) -> None:
        bibtex = "\n".join(f"@misc{{k{i}, title={{Work {i}}}}}" for i in range(21))
        with pytest.raises(ValueError, match="At most 20"):
            reference_service.parse_bibtex_entries(bibtex)

    def test_ignores_bibtex_directives_that_are_not_works(self) -> None:
        parsed = reference_service.parse_bibtex_entries(
            '@string{jmlr = "Journal of ML Research"}\n'
            '@comment{Generated by a reference manager}\n'
            '@article{paper, title={Real Work}}'
        )
        assert [entry["cite_key"] for entry in parsed] == ["paper"]


@pytest.mark.asyncio
class TestCrossrefCitationSearch:
    async def test_parses_best_result_and_uses_fixed_provider_url(self) -> None:
        response = MagicMock(status_code=200)
        response.json.return_value = {
            "message": {
                "items": [{
                    "DOI": "10.5555/result",
                    "title": ["Canonical Work"],
                    "author": [{"given": "Ada", "family": "Lovelace"}],
                    "issued": {"date-parts": [[1843, 1, 1]]},
                }]
            }
        }
        client = MagicMock()
        client.__aenter__ = AsyncMock(return_value=client)
        client.__aexit__ = AsyncMock(return_value=None)
        client.get = AsyncMock(return_value=response)
        with (
            patch("app.services.reference_service.cache_manager.get", AsyncMock(return_value=None)),
            patch("app.services.reference_service.cache_manager.set", AsyncMock()),
            patch("app.services.reference_service.httpx.AsyncClient", return_value=client),
        ):
            result = await reference_service.search_crossref("Canonical Work", "Lovelace, Ada")

        assert result["identifier"] == "10.5555/result"
        assert result["authors"] == "Lovelace, Ada"
        assert result["year"] == 1843
        assert client.get.await_args.args[0] == "https://api.crossref.org/works"
        assert client.get.await_args.kwargs["params"]["rows"] == 1

    async def test_empty_search_result_is_not_found(self) -> None:
        response = MagicMock(status_code=200)
        response.json.return_value = {"message": {"items": []}}
        client = MagicMock()
        client.__aenter__ = AsyncMock(return_value=client)
        client.__aexit__ = AsyncMock(return_value=None)
        client.get = AsyncMock(return_value=response)
        with (
            patch("app.services.reference_service.cache_manager.get", AsyncMock(return_value=None)),
            patch("app.services.reference_service.httpx.AsyncClient", return_value=client),
        ):
            with pytest.raises(ValueError, match="No scholarly match"):
                await reference_service.search_crossref("Missing Work")

    async def test_malformed_provider_payload_is_rejected(self) -> None:
        response = MagicMock(status_code=200)
        response.json.return_value = []
        client = MagicMock()
        client.__aenter__ = AsyncMock(return_value=client)
        client.__aexit__ = AsyncMock(return_value=None)
        client.get = AsyncMock(return_value=response)
        with (
            patch("app.services.reference_service.cache_manager.get", AsyncMock(return_value=None)),
            patch("app.services.reference_service.httpx.AsyncClient", return_value=client),
        ):
            with pytest.raises(ValueError, match="malformed"):
                await reference_service.search_crossref("Broken Work")


@pytest.mark.asyncio
class TestCitationVerificationEndpoint:
    async def test_exact_doi_is_verified(self, client: AsyncClient) -> None:
        with patch.object(reference_service, "fetch_doi", AsyncMock(return_value=MATCHED)):
            response = await client.post(
                "/references/verify",
                json={"bibtex": """@article{vaswani,
                    title={{Attention Is All You Need}},
                    author={Ashish Vaswani and Noam Shazeer},
                    year={2017}, doi={10.5555/3295222.3295349}}"""},
            )
        assert response.status_code == 200
        result = response.json()["results"][0]
        assert result["status"] == "verified"
        assert result["identifier"] == "10.5555/3295222.3295349"
        assert result["title_similarity"] == 1.0

    async def test_metadata_mismatches_are_explained(self, client: AsyncClient) -> None:
        with patch.object(reference_service, "fetch_doi", AsyncMock(return_value=MATCHED)):
            response = await client.post(
                "/references/verify",
                json={"bibtex": """@article{wrong,
                    title={A Completely Different Paper},
                    author={Turing, Alan}, year={2024}, doi={10.5555/example}}"""},
            )
        result = response.json()["results"][0]
        assert result["status"] == "mismatch"
        assert response.json()["mismatched"] == 1
        assert any("Title" in issue for issue in result["issues"])
        assert any("Year" in issue for issue in result["issues"])
        assert any("Authors" in issue for issue in result["issues"])

    async def test_identifier_free_entry_searches_crossref(self, client: AsyncClient) -> None:
        search_result = {**MATCHED, "identifier": "10.5555/canonical"}
        search = AsyncMock(return_value=search_result)
        with patch.object(reference_service, "search_crossref", search):
            response = await client.post(
                "/references/verify",
                json={"bibtex": """@article{searchme,
                    title={Attention Is All You Need},
                    author={Vaswani, Ashish}, year={2017}}"""},
            )
        assert response.json()["results"][0]["status"] == "verified"
        search.assert_awaited_once()

    async def test_arxiv_eprint_uses_arxiv_record(self, client: AsyncClient) -> None:
        fetch = AsyncMock(return_value=MATCHED)
        with patch.object(reference_service, "fetch_arxiv", fetch):
            response = await client.post(
                "/references/verify",
                json={"bibtex": """@misc{attention,
                    title={Attention Is All You Need}, year={2017},
                    eprint={1706.03762}, archivePrefix={arXiv}}"""},
            )
        result = response.json()["results"][0]
        assert result["status"] == "verified"
        assert result["source"] == "arxiv"
        assert result["identifier"] == "1706.03762"

    async def test_missing_record_is_not_a_server_error(self, client: AsyncClient) -> None:
        with patch.object(
            reference_service,
            "fetch_doi",
            AsyncMock(side_effect=ValueError("DOI not found: 10.9999/missing (HTTP 404)")),
        ):
            response = await client.post(
                "/references/verify",
                json={"bibtex": "@misc{missing, doi={10.9999/missing}}"},
            )
        assert response.status_code == 200
        assert response.json()["results"][0]["status"] == "not_found"

    async def test_entry_without_lookup_metadata_is_not_found(self, client: AsyncClient) -> None:
        response = await client.post(
            "/references/verify", json={"bibtex": "@misc{empty, note={No metadata}}"}
        )
        result = response.json()["results"][0]
        assert result["status"] == "not_found"
        assert "required" in result["issues"][0]

    async def test_invalid_year_is_reported_as_mismatch(self, client: AsyncClient) -> None:
        with patch.object(reference_service, "fetch_doi", AsyncMock(return_value=MATCHED)):
            response = await client.post(
                "/references/verify",
                json={"bibtex": """@misc{badyear, title={Attention Is All You Need},
                    year={twenty}, doi={10.5555/example}}"""},
            )
        result = response.json()["results"][0]
        assert result["status"] == "mismatch"
        assert any("four-digit" in issue for issue in result["issues"])

    async def test_malformed_and_empty_payloads_are_rejected(self, client: AsyncClient) -> None:
        malformed = await client.post(
            "/references/verify", json={"bibtex": "@article{broken, title={Oops}"}
        )
        empty = await client.post("/references/verify", json={"bibtex": ""})
        assert malformed.status_code == 422
        assert empty.status_code == 422

    async def test_more_than_twenty_entries_is_rejected(self, client: AsyncClient) -> None:
        bibtex = "\n".join(f"@misc{{k{i}, title={{Work {i}}}}}" for i in range(21))
        response = await client.post("/references/verify", json={"bibtex": bibtex})
        assert response.status_code == 422
