"""Consistency tests for the production deploy path.

These guard the class of failure where the image, the reverse proxy, the compose
healthcheck and the k8s probes each pick a different port / env var name and the
whole stack silently fails to come up. Nothing here needs a running cluster.
"""

import json
import re
import subprocess
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]

BACKEND_PORT = "8030"
FRONTEND_PORT = "5180"


def _read(relative: str) -> str:
    return (REPO_ROOT / relative).read_text()


def _load_all(relative: str) -> list:
    return [doc for doc in yaml.safe_load_all(_read(relative)) if doc]


def _k8s_manifests() -> list:
    docs = []
    for path in sorted((REPO_ROOT / "k8s").rglob("*.yaml")):
        docs.extend(doc for doc in yaml.safe_load_all(path.read_text()) if doc)
    return docs


def _containers(doc: dict) -> list:
    if doc.get("kind") != "Deployment":
        return []
    return doc["spec"]["template"]["spec"]["containers"]


def _env_names(container: dict) -> set:
    return {entry["name"] for entry in container.get("env", [])}


def _requirement_names(relative: str) -> set[str]:
    def normalize(name: str) -> str:
        return re.sub(r"[-_.]+", "-", name.lower())

    names: set[str] = set()
    for raw in _read(relative).splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue
        match = re.match(r"([A-Za-z0-9][A-Za-z0-9_.-]*)", line)
        if match:
            names.add(normalize(match.group(1)))
    return names


def _locked_names(relative: str) -> set[str]:
    def normalize(name: str) -> str:
        return re.sub(r"[-_.]+", "-", name.lower())

    return {
        normalize(match.group(1))
        for match in re.finditer(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==", _read(relative), re.MULTILINE)
    }


def _pinned_requirements(relative: str) -> dict[str, str]:
    def normalize(name: str) -> str:
        return re.sub(r"[-_.]+", "-", name.lower())

    pinned: dict[str, str] = {}
    for raw in _read(relative).splitlines():
        line = raw.strip()
        match = re.match(r"([A-Za-z0-9][A-Za-z0-9_.-]*)==([^\s;]+)", line)
        if match:
            pinned[normalize(match.group(1))] = match.group(2)
    return pinned


def test_shipped_workflow_actions_are_pinned_to_commit_shas():
    """Mutable action tags are a supply-chain execution boundary."""
    workflows = ("ci.yml", "deploy-modal.yml", "publish-tui.yml", "release.yml")
    use_pattern = re.compile(r"^\s*-?\s*uses:\s*[^\s@]+@([^\s#]+)", re.MULTILINE)
    for workflow in workflows:
        refs = use_pattern.findall(_read(f".github/workflows/{workflow}"))
        assert refs, workflow
        assert all(re.fullmatch(r"[0-9a-f]{40}", ref) for ref in refs), (
            workflow,
            refs,
        )


def test_ci_audits_the_complete_javascript_dependency_graph():
    """Development dependencies execute in CI and need the same advisory gate."""
    ci = _read(".github/workflows/ci.yml")
    assert "pnpm audit --audit-level low" in ci


def test_python_lock_inputs_are_hash_verified_and_cover_every_direct_dependency():
    """Human-edited requirements must never silently outrun generated locks."""
    production = _read("backend/requirements.lock")
    development = _read("backend/requirements-dev.lock")
    for lock in (production, development):
        assert "--hash=sha256:" in lock
        assert "# This file was autogenerated by uv" in lock
        assert "-r requirements.txt" not in lock.splitlines()[:4]
    prod_names = _requirement_names("backend/requirements.txt")
    dev_names = _requirement_names("backend/requirements-dev.txt") | prod_names
    assert prod_names <= _locked_names("backend/requirements.lock")
    assert dev_names <= _locked_names("backend/requirements-dev.lock")
    locked_versions = {
        re.sub(r"[-_.]+", "-", match.group(1).lower()): match.group(2)
        for match in re.finditer(
            r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==([^\s]+)", production, re.MULTILINE
        )
    }
    assert _pinned_requirements("backend/requirements.txt") == {
        name: locked_versions[name] for name in _pinned_requirements("backend/requirements.txt")
    }

    for relative in ("backend/Dockerfile", "backend/Dockerfile.prod"):
        dockerfile = _read(relative)
        assert "requirements.lock" in dockerfile or "requirements-dev.lock" in dockerfile
        assert "pip install --no-cache-dir -r requirements.txt" not in dockerfile
    modal = _read("backend/modal_app.py")
    assert modal.count('pip_install_from_requirements("requirements.lock"') == 4
    assert modal.count('extra_options="--require-hashes"') == 4
    assert 'python_version="3.12"' in modal

    ci = _read(".github/workflows/ci.yml")
    assert "uv pip install -r requirements-dev.txt" not in ci
    assert ci.count("uv pip sync --require-hashes --verify-hashes requirements-dev.lock") == 4
    assert "uv pip compile --python-version 3.12 --generate-hashes" in ci
    assert "--custom-compile-command" in ci
    assert 'diff -u requirements.lock "$lock_tmp/requirements.lock"' in ci
    assert 'diff -u requirements-dev.lock "$lock_tmp/requirements-dev.lock"' in ci
    assert "pip install -r requirements.txt" not in _read("backend/setup.sh")
    assert "requirements-dev.lock" in _read("docker-compose.test.yml")


def test_vercel_certification_is_sha_exact_bounded_and_cache_proof():
    workflow = _read(".github/workflows/verify-vercel.yml")
    route = _read("frontend/src/app/api/deployment-identity/route.ts")
    dockerfile = _read("frontend/Dockerfile.prod")
    release = _read(".github/workflows/release.yml")

    assert "workflow_run:" in workflow
    assert "workflows: [CI]" in workflow
    assert "branches: [main]" in workflow
    assert "conclusion == 'success'" in workflow
    assert "contents: read" in workflow and "actions: read" in workflow
    assert "^[0-9a-f]{40}$" in workflow
    assert "commits/main --jq .sha" in workflow
    assert "Skipping stale CI run" in workflow
    assert "readyState == \"READY\"" in workflow
    assert "checksState" in workflow and "checksConclusion" in workflow
    assert "seq 1 30" in workflow and "sleep 20" in workflow
    assert "VERCEL_GIT_COMMIT_SHA" in route
    assert "BUILD_VERSION" in route
    assert "SHA_PATTERN = /^[0-9a-f]{40}$/" in route
    assert "toLowerCase()" in route
    assert "'unknown'" in route
    assert "status: commitSha ? 200 : 503" in route
    assert "'Cache-Control': 'no-store, max-age=0'" in route
    assert "'Vercel-CDN-Cache-Control': 'no-store'" in route
    assert "ARG BUILD_VERSION=local" in dockerfile
    assert "BUILD_VERSION=$BUILD_VERSION" in dockerfile
    assert "BUILD_VERSION=${{ github.sha }}" in release


def test_node_package_manager_is_pinned_consistently():
    """CI and production images must resolve the lock with the same pnpm release."""
    package = json.loads(_read("package.json"))
    package_manager = package["packageManager"]
    assert package_manager.startswith("pnpm@")
    pnpm_version = package_manager.removeprefix("pnpm@")
    assert re.fullmatch(r"\d+\.\d+\.\d+", pnpm_version)

    dockerfile = _read("frontend/Dockerfile.prod")
    assert f"corepack prepare pnpm@{pnpm_version} --activate" in dockerfile
    for workflow_path in (".github/workflows/ci.yml", ".github/workflows/publish-tui.yml"):
        workflow = _read(workflow_path)
        versions = re.findall(r"^\s+version:\s*([^\s#]+)", workflow, re.MULTILINE)
        assert versions
        assert set(versions) == {pnpm_version}


def test_canonical_ci_covers_every_branch_and_keeps_pr_jobs_secret_free():
    """Every ref gets the same CI contract, including untrusted pull requests."""
    ci = _read(".github/workflows/ci.yml")

    # These null event maps intentionally omit branch/path filters.  Keep this
    # assertion textual because PyYAML 1.1 treats the YAML key ``on`` as a bool.
    assert re.search(r"^\s*push:\s*$", ci, re.MULTILINE)
    assert re.search(r"^\s*pull_request:\s*$", ci, re.MULTILINE)
    assert not re.search(r"^\s+(branches|branches-ignore|paths|paths-ignore):", ci, re.MULTILINE)

    # A pull request from a fork can execute repository workflow code.  CI must
    # therefore use only deterministic literals, never repository secrets.
    assert "${{ secrets." not in ci


def test_modal_deploy_requires_main_ci_and_skips_stale_automatic_runs():
    """Deployment provenance and ordering guards must precede every mutation."""
    modal = _read(".github/workflows/deploy-modal.yml")

    assert "contents: read" in modal
    assert "actions: read" in modal
    assert "git merge-base --is-ancestor" in modal
    assert "actions/workflows/ci.yml/runs?head_sha=" in modal
    assert "conclusion == \"success\"" in modal
    assert "id: freshness" in modal
    assert 'commits/main" --jq .sha' in modal
    assert "if: steps.freshness.outputs.current == 'true'" in modal
    assert 'modal deploy --env main --strategy rolling --tag "$DEPLOY_SHA"' in modal


def test_release_requires_main_ancestry_and_ci_before_publishing_immutable_tags():
    """A tag cannot publish images or a release until its provenance is checked."""
    release = _read(".github/workflows/release.yml")

    assert "validate-release:" in release
    assert "actions: read" in release
    assert "git merge-base --is-ancestor" in release
    assert "actions/workflows/ci.yml/runs?head_sha=" in release
    assert "needs: [validate-release]" in release
    assert "needs: [validate-release, build-backend, build-frontend]" in release
    assert "ref: ${{ github.sha }}" in release
    assert release.count("type=raw,value=${{ github.ref_name }}") == 2
    assert "type=semver,pattern={{version}}" in release
    assert "type=sha,prefix=sha-" in release
    assert release.count("flavor: latest=false") == 2
    assert "type=raw,value=latest" not in release
    assert "pattern={{major}}.{{minor}}" not in release


def test_production_public_origin_contract_uses_latexy_xyz_everywhere():
    """Released browser URLs, K8s config, and backend CORS share one origin."""
    release = _read(".github/workflows/release.yml")
    namespace = next(
        doc
        for doc in _load_all("k8s/namespace.yaml")
        if doc.get("kind") == "ConfigMap" and doc["metadata"]["name"] == "latexy-config"
    )
    config = _read("backend/app/core/config.py")
    tenant = _read("backend/app/middleware/tenant_middleware.py")
    frontend_middleware = _read("frontend/src/middleware.ts")

    assert "wss://latexy.xyz" in release
    assert namespace["data"]["ws-url"] == "wss://latexy.xyz"
    assert namespace["data"]["frontend-url"] == "https://latexy.xyz"
    assert namespace["data"]["cors-origins"] == '["https://latexy.xyz","https://www.latexy.xyz"]'
    assert '"https://latexy.xyz"' in config
    assert '"https://latexy.com"' not in config
    assert '"latexy.xyz", "www.latexy.xyz"' in tenant
    assert "hostname === 'latexy.com'" not in frontend_middleware


def test_production_compose_requires_an_immutable_image_revision():
    """Self-hosting must not silently pull a tag the release job never publishes."""
    compose = _read("docker-compose.prod.yml")
    env_example = _env_production()

    assert compose.count("${LATEXY_VERSION:?set LATEXY_VERSION to an immutable release tag or sha}") == 5
    assert "${LATEXY_VERSION:-latest}" not in compose
    assert env_example["LATEXY_VERSION"] == ""


def test_frontend_production_image_uses_the_root_frozen_workspace_lockfile():
    """The image must resolve the same monorepo dependency graph as CI."""
    dockerfile = _read("frontend/Dockerfile.prod")
    dockerignore = _read("frontend/Dockerfile.prod.dockerignore")
    compose = _read("docker-compose.prod.yml")
    release = _read(".github/workflows/release.yml")

    assert "COPY .npmrc package.json pnpm-lock.yaml pnpm-workspace.yaml ./" in dockerfile
    assert "COPY frontend/package.json ./frontend/package.json" in dockerfile
    assert "RUN pnpm install --frozen-lockfile" in dockerfile
    assert "--no-frozen-lockfile" not in dockerfile
    assert "ARG NEXT_PUBLIC_APP_URL=https://latexy.xyz" in dockerfile
    assert "NEXT_PUBLIC_APP_URL=${{ vars.NEXT_PUBLIC_APP_URL || 'https://latexy.xyz' }}" in release
    for excluded in (
        "**/node_modules",
        "**/.env.*",
        "**/.git/**",
        "**/.next/**",
        "**/coverage/**",
        "**/playwright-report/**",
        "**/test-results/**",
        "**/reports/**",
        "**/results/**",
        "**/dist/**",
    ):
        assert excluded in dockerignore
    for required in (
        "package.json",
        ".npmrc",
        "pnpm-lock.yaml",
        "pnpm-workspace.yaml",
        "patches/",
        "frontend/package.json",
        "packages/browser-extension/package.json",
        "packages/tui/package.json",
        "frontend/src/",
        "frontend/public/",
    ):
        assert required not in dockerignore
    assert "context: ." in compose
    assert "context: ." in release


def test_self_host_builds_before_migration_and_starts_without_rebuilding():
    script = _read("scripts/self-host-up.sh")
    build = script.index('"${compose[@]}" build frontend backend celery-worker celery-beat flower')
    stateful = script.index('"${compose[@]}" up -d --wait postgres redis minio tempo')
    minio_init = script.index('"${compose[@]}" run --rm --no-deps minio-init')
    migrate = script.index('"${compose[@]}" run --rm --no-deps backend alembic upgrade head')
    start = script.index('"${compose[@]}" up -d --no-build --remove-orphans')

    assert build < stateful < minio_init < migrate < start
    assert "one-shot" in script
    assert "up -d --build --remove-orphans" not in script


def test_legacy_deploy_script_rejects_unconfigured_staging_topology():
    script = _read("scripts/deploy/deploy.sh")
    assert 'case "$DEPLOY_ENV" in' in script
    assert "Staging topology is not configured; refusing to use production Compose" in script
    assert "staging)" in script


# --------------------------------------------------------------------------- #
#  Ports                                                                       #
# --------------------------------------------------------------------------- #


def test_backend_image_listens_on_the_port_everyone_targets():
    dockerfile = _read("backend/Dockerfile.prod")
    assert f"ENV PORT={BACKEND_PORT}" in dockerfile
    assert f"EXPOSE {BACKEND_PORT}" in dockerfile
    # uvicorn must take the port from the env var, not a second hardcoded value.
    assert '--port \\"${PORT}\\"' in dockerfile
    assert "8000" not in dockerfile


def test_frontend_image_listens_on_the_port_nginx_proxies_to():
    dockerfile = _read("frontend/Dockerfile.prod")
    assert f"PORT={FRONTEND_PORT}" in dockerfile
    assert f"EXPOSE {FRONTEND_PORT}" in dockerfile
    assert "3000" not in dockerfile


def test_backend_production_image_contains_advertised_ocr_runtime():
    dockerfile = _read("backend/Dockerfile.prod")
    assert "tesseract-ocr" in dockerfile
    assert "tesseract-ocr-eng" in dockerfile
    assert "poppler-utils" in dockerfile


def test_modal_compiler_image_installs_pinned_atkinson_font_support():
    modal_app = _read("backend/modal_app.py")
    assert "https://tug.ctan.org/install/fonts/atkinson.tds.zip" in modal_app
    assert re.search(r'_ATKINSON_TDS_SHA256 = "[0-9a-f]{64}"', modal_app)
    assert "sha256sum -c -" in modal_app
    assert "updmap-sys --enable Map=atkinson.map" in modal_app
    assert "api_image = (\n    texlive_image" in modal_app
    assert "latex_image = (\n    texlive_image" in modal_app


def test_hosted_font_matrix_covers_every_frontend_enabled_package():
    frontend_fonts = _read("frontend/src/lib/latex-preamble.ts")
    configured = re.search(
        r"HOSTED_LATEX_FONT_PACKAGES = new Set\(\[(.*?)\]\)",
        frontend_fonts,
        re.DOTALL,
    )
    assert configured is not None
    frontend_packages = set(re.findall(r"'([^']+)'", configured.group(1)))

    matrix = _read("backend/scripts/verify-hosted-fonts.sh")
    scripted = re.search(r"packages=\(([^)]+)\)", matrix)
    assert scripted is not None
    assert set(scripted.group(1).split()) == frontend_packages
    assert "engines=(pdflatex xelatex lualatex)" in matrix


def test_ci_enforces_the_pdf_extraction_contract_for_every_seeded_template():
    ci = _read(".github/workflows/ci.yml")
    verifier = _read("backend/scripts/verify-template-extraction.sh")

    assert "template-pdf-contract:" in ci
    assert "bash scripts/verify-template-extraction.sh" in ci
    for dependency in ("texlive-luatex", "fonts-lohit-deva", "poppler-utils"):
        assert dependency in ci

    assert "find \"$templates_root\" -type f -name '*.tex'" in verifier
    assert 'pdffonts "$pdf_path"' in verifier
    assert 'pdftotext -layout "$pdf_path"' in verifier
    assert '$6 != "yes"' in verifier
    assert "word_count < 25" in verifier
    assert "leading_separator_count > 0" in verifier


def test_devanagari_runtime_and_template_use_explicit_harfbuzz_shaping():
    modal_app = _read("backend/modal_app.py")
    dockerfile = _read("backend/Dockerfile.prod")
    template = _read("backend/app/data/templates/ats_safe/hindi_professional.tex")

    assert '"fonts-lohit-deva"' in modal_app
    assert "fonts-lohit-deva" in dockerfile
    assert "Renderer=HarfBuzz,Script=Devanagari" in template
    assert "Noto Sans Devanagari" in template
    assert "BoldFont={Noto Sans Devanagari Bold}" in template
    assert "ItalicFeatures={FakeSlant=0.15}" in template
    assert r"\babelprovide[onchar=ids fonts]{english}" in template
    assert r"\renewcommand{\bfdefault}{b}" in template
    assert r"\setlist[itemize]{label=\foreignlanguage{english}{\textbullet}}" in template
    assert r"\usepackage[english,hindi,provide=*]{babel}" in template
    verifier = _read("backend/scripts/verify-template-extraction.sh")
    for expected_text in ("आरव शर्मा", "व्यावसायिक सारांश", "भुगतान मंच"):
        assert expected_text in verifier


def test_make_builds_the_shipped_images_and_uses_the_canonical_infra():
    makefile = _read("Makefile")
    assert "COMPOSE_FILE      := $(ROOT_COMPOSE)" in makefile
    assert "$(BACKEND_DIR)/Dockerfile.prod" in makefile
    assert "$(FRONTEND_DIR)/Dockerfile.prod" in makefile
    assert "ghcr.io/your-org" not in makefile
    assert "logs -f worker" in makefile


def test_worktree_app_slots_do_not_recreate_shared_infra():
    script = _read("scripts/worktree-up.sh")
    assert ('docker compose -p "$PROJECT_NAME" up -d --no-deps backend worker beat frontend flower') in script


def test_index_migration_downgrades_only_drop_owned_indexes():
    migration_0032 = _read("backend/alembic/versions/0032_session_and_performance_indexes.py")
    downgrade_0032 = migration_0032.split("def downgrade() -> None:", 1)[1]
    assert "idx_session_user_id" not in downgrade_0032
    assert "idx_account_user_id" not in downgrade_0032

    migration_0030 = _read("backend/alembic/versions/0030_add_missing_indexes.py")
    downgrade_0030 = migration_0030.split("def downgrade() -> None:", 1)[1]
    assert "DROP INDEX IF EXISTS idx_session_user_id" in downgrade_0030
    assert "DROP INDEX IF EXISTS idx_account_user_id" in downgrade_0030


def test_hybrid_dev_uses_its_docker_redis_not_a_host_daemon():
    """A native Redis on 6379 must not silently capture Latexy's local state."""
    compose = yaml.safe_load(_read("docker-compose.yml"))
    assert compose["services"]["redis"]["ports"] == ["${REDIS_PORT:-6380}:6379"]

    dev = _read("scripts/dev.sh")
    assert 'DEV_REDIS_PORT="${REDIS_PORT:-6380}"' in dev
    assert "redis://localhost:${DEV_REDIS_PORT}/0" in dev
    assert "redis://localhost:${DEV_REDIS_PORT}/1" in dev
    assert 'NEXT_ENV_STAMP="$NEXT_CACHE_DIR/.latexy-dev-env"' in dev
    assert 'rm -rf "$NEXT_CACHE_DIR"' in dev

    smoke = _read("scripts/ci/full-stack-smoke.sh")
    assert 'REDIS_PORT="${REDIS_PORT:-6380}"' in smoke
    assert "redis://localhost:${REDIS_PORT}/0" in smoke
    assert "redis://localhost:${REDIS_PORT}/1" in smoke

    # GitHub's service container intentionally stays on its isolated runner's
    # standard port; make that override explicit when local test defaults use
    # the project-specific 6380 binding.
    ci = yaml.safe_load(_read(".github/workflows/ci.yml"))
    assert ci["jobs"]["backend-test"]["env"]["TEST_REDIS_URL"] == ("redis://localhost:6379/15")
    assert ci["jobs"]["backend-test"]["env"]["TEST_REDIS_CACHE_URL"] == ("redis://localhost:6379/14")


def test_nginx_upstreams_match_the_container_ports():
    conf = _read("nginx/nginx.conf")
    assert f"server backend:{BACKEND_PORT}" in conf
    assert f"server frontend:{FRONTEND_PORT}" in conf


@pytest.mark.parametrize(
    "deployment,port",
    [("latexy-backend", BACKEND_PORT), ("latexy-frontend", FRONTEND_PORT)],
)
def test_k8s_container_ports_and_probes_agree(deployment, port):
    doc = next(d for d in _k8s_manifests() if d.get("kind") == "Deployment" and d["metadata"]["name"] == deployment)
    container = _containers(doc)[0]
    assert container["ports"][0]["containerPort"] == int(port)
    for probe in ("livenessProbe", "readinessProbe"):
        assert container[probe]["httpGet"]["port"] == int(port)
    assert {"name": "PORT", "value": port} in container["env"]


# --------------------------------------------------------------------------- #
#  Required settings                                                           #
# --------------------------------------------------------------------------- #

# Settings.model_post_init raises at import time without these.
REQUIRED_BACKEND_ENV = {
    "DATABASE_URL",
    "BETTER_AUTH_SECRET",
    "JWT_SECRET_KEY",
    "API_KEY_ENCRYPTION_KEY",
}

# Every service that imports app.core.config.
PYTHON_COMPOSE_SERVICES = ["backend", "celery-worker", "celery-beat", "flower"]
PYTHON_K8S_DEPLOYMENTS = ["latexy-backend", "celery-worker", "celery-beat", "flower"]


# The API pod enqueues compile/optimize/ATS work itself. Without an explicit
# broker it falls back to config.py's redis://localhost:6379 defaults, which
# point at nothing inside a k8s pod.
REQUIRED_BROKER_ENV = {
    "CELERY_BROKER_URL",
    "CELERY_RESULT_BACKEND",
    "REDIS_URL",
    "REDIS_CACHE_URL",
}


@pytest.mark.parametrize("service", PYTHON_COMPOSE_SERVICES)
def test_compose_services_pass_every_required_setting(service):
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    env = {entry.split("=", 1)[0] for entry in compose["services"][service]["environment"]}
    assert REQUIRED_BACKEND_ENV <= env


def test_api_pod_points_celery_at_the_shared_broker():
    """The API enqueues tasks itself; the localhost defaults are a dead broker."""
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    env = {entry.split("=", 1)[0] for entry in compose["services"]["backend"]["environment"]}
    assert REQUIRED_BROKER_ENV <= env

    doc = next(
        d for d in _k8s_manifests() if d.get("kind") == "Deployment" and d["metadata"]["name"] == "latexy-backend"
    )
    assert REQUIRED_BROKER_ENV <= _env_names(_containers(doc)[0])


def test_k8s_broker_env_references_a_secret_key_deploy_sh_creates():
    """A secretKeyRef to a missing key leaves the pod stuck in CreateContainerConfigError."""
    deploy_sh = _read("k8s/deploy.sh")
    referenced = {
        entry["valueFrom"]["secretKeyRef"]["key"]
        for doc in _k8s_manifests()
        for container in _containers(doc)
        for entry in container.get("env", [])
        if entry.get("valueFrom", {}).get("secretKeyRef", {}).get("name") == "latexy-secrets"
    }
    for key in sorted(referenced):
        assert f"--from-literal={key}=" in deploy_sh, key


@pytest.mark.parametrize("deployment", PYTHON_K8S_DEPLOYMENTS)
def test_k8s_python_deployments_pass_every_required_setting(deployment):
    doc = next(d for d in _k8s_manifests() if d.get("kind") == "Deployment" and d["metadata"]["name"] == deployment)
    assert REQUIRED_BACKEND_ENV <= _env_names(_containers(doc)[0])


# The frontend container *is* the auth server: nginx proxies /api/auth/ and
# /api/byok/ to it. frontend/src/lib/auth.ts throws without BETTER_AUTH_SECRET
# in production and opens a pg Pool straight from DATABASE_URL; middleware.ts
# and app/api/byok/_forward.ts fetch() BACKEND_URL server-side, which must be an
# absolute URL (NEXT_PUBLIC_API_URL is the same-origin path "/api").
REQUIRED_FRONTEND_ENV = {
    "BETTER_AUTH_SECRET",
    "DATABASE_URL",
    "BETTER_AUTH_URL",
    "BACKEND_URL",
    # lib/email.ts refuses the console-logging fallback in production, so
    # sign-up and password reset throw without a provider key.
    "RESEND_API_KEY",
}


def test_compose_frontend_can_actually_serve_auth():
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    env = {entry.split("=", 1)[0] for entry in compose["services"]["frontend"]["environment"]}
    assert REQUIRED_FRONTEND_ENV <= env


def test_k8s_frontend_can_actually_serve_auth():
    doc = next(
        d for d in _k8s_manifests() if d.get("kind") == "Deployment" and d["metadata"]["name"] == "latexy-frontend"
    )
    assert REQUIRED_FRONTEND_ENV <= _env_names(_containers(doc)[0])


def test_frontend_backend_url_is_absolute_and_reachable_in_network():
    """`fetch('/api/...')` from Node throws 'Failed to parse URL'."""
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    compose_value = next(
        entry.split("=", 1)[1]
        for entry in compose["services"]["frontend"]["environment"]
        if entry.startswith("BACKEND_URL=")
    )
    assert compose_value == f"http://backend:{BACKEND_PORT}"

    doc = next(
        d for d in _k8s_manifests() if d.get("kind") == "Deployment" and d["metadata"]["name"] == "latexy-frontend"
    )
    k8s_value = next(entry["value"] for entry in _containers(doc)[0]["env"] if entry["name"] == "BACKEND_URL")
    assert k8s_value == f"http://latexy-backend-service:{BACKEND_PORT}"


def test_production_flag_uses_the_variable_config_actually_reads():
    """FASTAPI_ENV is read nowhere; Settings reads ENVIRONMENT."""
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    for service in PYTHON_COMPOSE_SERVICES:
        env = compose["services"][service]["environment"]
        assert "ENVIRONMENT=production" in env
        assert not any(entry.startswith("FASTAPI_ENV=") for entry in env)

    for deployment in PYTHON_K8S_DEPLOYMENTS:
        doc = next(d for d in _k8s_manifests() if d.get("kind") == "Deployment" and d["metadata"]["name"] == deployment)
        names = _env_names(_containers(doc)[0])
        assert "ENVIRONMENT" in names
        assert "FASTAPI_ENV" not in names


def test_backend_trusts_the_bundled_nginx_for_client_ips():
    """Without this, every real user shares one 'untrusted proxy' rate-limit bucket.

    nginx always sets X-Forwarded-For, so with TRUST_PROXY_HEADERS unset the whole
    user base lands in a single bucket and one caller can 429 the site.
    """
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    assert "TRUST_PROXY_HEADERS=true" in compose["services"]["backend"]["environment"]

    backend = next(
        d for d in _k8s_manifests() if d.get("kind") == "Deployment" and d["metadata"]["name"] == "latexy-backend"
    )
    assert "TRUST_PROXY_HEADERS" in _env_names(_containers(backend)[0])

    # …and it is only trustworthy because nginx overwrites X-Real-IP itself.
    for conf in _nginx_configs().values():
        assert "proxy_set_header X-Real-IP $remote_addr;" in conf


def test_production_email_runtimes_receive_optional_provider_configuration():
    required_email_env = {
        "EMAIL_ENABLED",
        "EMAIL_PROVIDER",
        "RESEND_API_KEY",
        "EMAIL_FROM",
        "EMAIL_FROM_NAME",
        "SMTP_HOST",
        "SMTP_PORT",
        "SMTP_USER",
        "SMTP_PASSWORD",
    }
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    for service in ("backend", "celery-worker"):
        compose_env = {
            entry.split("=", 1)[0]
            for entry in compose["services"][service]["environment"]
        }
        assert required_email_env <= compose_env

    backend_compose_env = {
        entry.split("=", 1)[0]
        for entry in compose["services"]["backend"]["environment"]
    }
    assert {
        "GOOGLE_DRIVE_CLIENT_ID",
        "GOOGLE_DRIVE_CLIENT_SECRET",
        "GOOGLE_DRIVE_REDIRECT_URI",
    } <= backend_compose_env

    deployments = _k8s_manifests()
    k8s_by_name = {
        doc["metadata"]["name"]: doc
        for doc in deployments
        if doc.get("kind") == "Deployment"
    }
    for deployment_name in ("latexy-backend", "celery-worker"):
        assert required_email_env <= _env_names(
            _containers(k8s_by_name[deployment_name])[0]
        )
    assert {
        "GOOGLE_DRIVE_CLIENT_ID",
        "GOOGLE_DRIVE_CLIENT_SECRET",
        "GOOGLE_DRIVE_REDIRECT_URI",
    } <= _env_names(_containers(k8s_by_name["latexy-backend"])[0])


def test_k8s_nginx_service_preserves_the_client_source_address():
    """X-Real-IP is only worth trusting if $remote_addr is the client.

    A type: LoadBalancer Service without externalTrafficPolicy: Local is SNAT'd by
    kube-proxy, so $remote_addr — and therefore the X-Real-IP the backend trusts and
    nginx's own $binary_remote_addr limit_req zones — is the node IP. Every anonymous
    user behind a node would then share one rate-limit bucket, which is exactly the
    shared-bucket DoS TRUST_PROXY_HEADERS was supposed to remove. The alternative, for
    an L7 cloud LB in front, is recovering the client with the real_ip module.
    """
    service = next(
        d
        for d in _load_all("k8s/nginx/nginx.yaml")
        if d.get("kind") == "Service" and d["metadata"]["name"] == "nginx-service"
    )
    conf = _nginx_configs()["k8s"]
    assert service["spec"].get("externalTrafficPolicy") == "Local" or (
        "set_real_ip_from" in conf and "real_ip_header" in conf
    ), "nginx sees the node IP, not the client IP"


# --------------------------------------------------------------------------- #
#  Routing                                                                     #
# --------------------------------------------------------------------------- #


def _nginx_configs() -> dict:
    k8s_nginx = next(
        d
        for d in _load_all("k8s/nginx/nginx.yaml")
        if d.get("kind") == "ConfigMap" and d["metadata"]["name"] == "nginx-config"
    )
    return {
        "compose": _read("nginx/nginx.conf"),
        "k8s": k8s_nginx["data"]["nginx.conf"],
    }


@pytest.mark.parametrize("name", ["compose", "k8s"])
def test_api_prefix_is_stripped_before_reaching_fastapi(name):
    """`proxy_pass http://backend;` (no trailing slash) keeps the /api prefix
    and 404s on every REST call."""
    conf = _nginx_configs()[name]
    block = re.search(r"location /api/ \{(.*?)\n(\s*)\}", conf, re.S).group(1)
    assert "proxy_pass http://backend/;" in block


@pytest.mark.parametrize("name", ["compose", "k8s"])
def test_next_route_handlers_stay_on_the_frontend(name):
    conf = _nginx_configs()[name]
    for prefix in ("/api/auth/", "/api/byok/"):
        block = re.search(rf"location {re.escape(prefix)} \{{(.*?)\n(\s*)\}}", conf, re.S).group(1)
        assert "proxy_pass http://frontend;" in block


@pytest.mark.parametrize("name", ["compose", "k8s"])
def test_auth_prefix_is_not_under_the_strict_login_rate_limit(name):
    """`/api/auth/` also carries get-session, which useSession() fires on every
    page load from every page. Putting the whole prefix in the 5r/m `login`
    zone made the app unusable behind any shared/NAT IP."""
    conf = _nginx_configs()[name]
    block = re.search(r"location /api/auth/ \{(.*?)\n(\s*)\}", conf, re.S).group(1)
    assert "zone=api" in block
    assert "zone=login" not in block


@pytest.mark.parametrize("name", ["compose", "k8s"])
def test_credential_endpoints_keep_a_strict_rate_limit(name):
    """Brute-force protection must survive the get-session fix: the actual
    credential-submitting endpoints get exact-match blocks in `login`."""
    conf = _nginx_configs()[name]
    assert "zone=login" in conf
    for path in (
        "/api/auth/sign-in/email",
        "/api/auth/sign-up/email",
        "/api/auth/request-password-reset",
        "/api/auth/reset-password",
    ):
        block = re.search(rf"location = {re.escape(path)} \{{(.*?)\n(\s*)\}}", conf, re.S)
        assert block, f"{name}: no exact-match block for {path}"
        assert "zone=login" in block.group(1)
        assert "proxy_pass http://frontend;" in block.group(1)


@pytest.mark.parametrize("name", ["compose", "k8s"])
def test_websocket_location_matches_the_backend_route(name):
    """Backend serves /ws/jobs; the old /jobs/ws/ block was dead config."""
    conf = _nginx_configs()[name]
    assert "location /ws/ {" in conf
    assert "/jobs/ws/" not in conf


@pytest.mark.parametrize("name", ["compose", "k8s"])
def test_collab_socket_never_lands_in_the_rest_api_location(name):
    """`location /api/` carries `limit_conn 10` and a short read timeout.

    A permanently-open editor socket routed there burns one of ten per-IP
    connection slots per tab, so a handful of collaborators behind one NAT
    503s every REST call for that IP.
    """
    conf = _nginx_configs()[name]
    block = re.search(r"location /api/ws/ \{(.*?)\n(\s*)\}", conf, re.S)
    assert block, f"{name}: no websocket-capable location for /api/ws/"
    body = block.group(1)
    # Trailing slash: /api/ws/collab/<id> must reach the backend as /ws/collab/<id>.
    assert "proxy_pass http://backend/ws/;" in body
    assert "proxy_set_header Upgrade $http_upgrade;" in body
    assert 'proxy_set_header Connection "upgrade";' in body
    assert "limit_conn" not in body
    assert int(re.search(r"proxy_read_timeout (\d+)", body).group(1)) >= 3600


def test_collab_client_uses_the_websocket_origin_not_the_api_path():
    """In production NEXT_PUBLIC_API_URL is the same-origin path '/api', so
    deriving the collab socket from it produced wss://host/api/ws/collab."""
    editor = _read("frontend/src/components/LaTeXEditor.tsx")
    assert "getCollabWebSocketUrl()" in editor
    assert "NEXT_PUBLIC_API_URL" not in editor

    api_client = _read("frontend/src/lib/api-client.ts")
    builder = re.search(
        r"export function getCollabWebSocketUrl\(\): string \{(.*?)\n\}",
        api_client,
        re.S,
    )
    assert builder, "getCollabWebSocketUrl() is gone"
    assert "getWebSocketBase()}/ws/collab" in builder.group(1)


def test_plain_http_health_endpoint_is_not_a_redirect():
    """The compose healthcheck probes http://localhost:80/health."""
    conf = _read("nginx/nginx.conf")
    http_server = re.search(r"server \{\s*\n\s*listen 80;(.*?)\n    \}", conf, re.S)
    assert http_server, "no plain-HTTP server block found"
    assert "location /health {" in http_server.group(1)


def test_frontend_ws_url_build_arg_must_be_absolute():
    """`${NEXT_PUBLIC_WS_URL}/ws/jobs` is fed to `new URL()`, which rejects
    relative values — a baked '/ws' produced '/ws/ws/jobs' and threw."""
    dockerfile = _read("frontend/Dockerfile.prod")
    assert "ws://*|wss://*" in dockerfile
    assert "NEXT_PUBLIC_WS_URL=/ws" not in dockerfile
    assert "NEXT_PUBLIC_WS_URL=/ws" not in _read(".github/workflows/release.yml")


def test_release_never_passes_an_empty_ws_url_build_arg():
    """A missing `vars.NEXT_PUBLIC_WS_URL` renders empty and the Dockerfile
    guard then aborts the release build. Default to the same public origin
    k8s/namespace.yaml already hardcodes."""
    release = _read(".github/workflows/release.yml")
    line = next(ln for ln in release.splitlines() if "NEXT_PUBLIC_WS_URL=${{" in ln)
    default = re.search(r"\|\|\s*'(ws{1,2}s?://[^']+)'", line)
    assert default, f"no fallback for an unset repo variable: {line.strip()}"

    namespace = next(
        d
        for d in _load_all("k8s/namespace.yaml")
        if d.get("kind") == "ConfigMap" and d["metadata"]["name"] == "latexy-config"
    )
    assert default.group(1) == namespace["data"]["ws-url"]


# --------------------------------------------------------------------------- #
#  Secrets                                                                     #
# --------------------------------------------------------------------------- #


def _env_production() -> dict:
    values = {}
    for line in _read(".env.production.example").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value.split("  #")[0].strip()
    return values


def test_env_production_satisfies_every_hard_compose_guard():
    """release.yml deploys with `--env-file .env.production`; a `${VAR:?}` with
    no key there aborts `docker compose config/pull/up` before anything runs."""
    required = set(re.findall(r"\$\{([A-Z0-9_]+):\?", _read("docker-compose.prod.yml")))
    assert required, "no ${VAR:?} guards found — did the guards get dropped?"
    assert not required - set(_env_production())


def test_compose_bind_mount_sources_exist():
    """A missing bind source becomes a directory and can crash the container."""
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    missing = []
    for service, config in compose["services"].items():
        for volume in config.get("volumes", []):
            source = str(volume).split(":", 1)[0]
            if source.startswith("./") and not (REPO_ROOT / source).exists():
                missing.append(f"{service}:{source}")
    assert missing == []


def test_self_hosted_storage_and_pgvector_are_included():
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    assert compose["services"]["postgres"]["image"].startswith("pgvector/pgvector:")
    assert {"minio", "minio-init"} <= set(compose["services"])
    for service in ("backend", "celery-worker"):
        env = {entry.split("=", 1)[0] for entry in compose["services"][service]["environment"]}
        assert {"MINIO_ENDPOINT", "MINIO_ACCESS_KEY", "MINIO_SECRET_KEY", "MINIO_BUCKET"} <= env
        assert compose["services"][service]["depends_on"]["minio-init"]["condition"] == (
            "service_completed_successfully"
        )


def test_self_host_startup_validates_migrates_and_starts_the_stack():
    script = _read("scripts/self-host-up.sh")
    assert 'config --quiet' in script
    assert 'up -d --wait postgres redis minio tempo' in script
    assert 'run --rm --no-deps minio-init' in script
    assert 'build frontend backend celery-worker celery-beat flower' in script
    assert 'run --rm --no-deps backend alembic upgrade head' in script
    assert 'up -d --no-build --remove-orphans' in script
    assert 'nginx/ssl/latexy.crt' in script
    assert 'nginx/ssl/latexy.key' in script

    makefile = _read("Makefile")
    assert "self-host-up:" in makefile
    assert "bash scripts/self-host-up.sh" in makefile
    assert "--env-file .env.production -f $(ROOT_COMPOSE_PROD) up --build" in makefile


def test_observability_smoke_bootstraps_its_isolated_yaml_validator():
    """The dedicated CI job checks out code only; it installs no backend deps."""
    script = _read("scripts/ci/observability-smoke.sh")
    assert 'backend/.venv/bin/python' in script
    assert 'python3 -m venv "$VALIDATOR_VENV"' in script
    assert 'PyYAML==6.0.3' in script
    assert '"$VALIDATOR_PYTHON" - <<\'PY\'' in script


def test_runtime_production_env_is_untracked():
    ignore = _read(".gitignore").splitlines()
    assert ".env.production" in ignore
    assert (REPO_ROOT / ".env.production.example").is_file()


def test_env_production_cors_origins_is_the_json_array_pydantic_expects():
    """pydantic-settings parses List[str] as JSON; a comma-separated value
    raises SettingsError at import and crash-loops every Python service."""
    import json

    raw = _env_production()["CORS_ORIGINS"]
    parsed = json.loads(raw)
    assert isinstance(parsed, list) and parsed
    assert all(origin.startswith("https://") for origin in parsed), parsed


def test_env_production_ws_url_is_an_absolute_websocket_origin():
    """It is baked into the bundle and fed to `new URL()`."""
    assert _env_production()["NEXT_PUBLIC_WS_URL"].startswith(("ws://", "wss://"))


def test_compose_never_falls_back_to_a_default_credential():
    """Every secret must fail at config time rather than ship a guessable value."""
    compose = _read("docker-compose.prod.yml")
    for var in ("POSTGRES_PASSWORD", "GRAFANA_PASSWORD", "FLOWER_PASSWORD"):
        weak = re.findall(rf"\$\{{{var}:-[^}}]*\}}", compose)
        assert not weak, weak
        assert f"${{{var}:?" in compose


def test_unauthenticated_monitoring_ports_are_not_published_publicly():
    """prometheus/alertmanager/tempo ship no auth; grafana is an admin UI."""
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    for service in ("prometheus", "alertmanager", "tempo", "grafana"):
        for mapping in compose["services"][service].get("ports", []):
            assert str(mapping).startswith("127.0.0.1:"), f"{service}: {mapping}"


def test_flower_operator_ui_is_loopback_only():
    compose = yaml.safe_load(_read("docker-compose.prod.yml"))
    assert all(str(mapping).startswith("127.0.0.1:") for mapping in compose["services"]["flower"]["ports"])


def test_no_secret_manifests_are_committed():
    """Secrets are provisioned by k8s/deploy.sh, never checked in."""
    committed = [(doc["metadata"]["name"]) for doc in _k8s_manifests() if doc.get("kind") == "Secret"]
    assert committed == []


def test_k8s_images_match_what_the_release_pipeline_publishes():
    release = _read(".github/workflows/release.yml")
    deploy_sh = _read("k8s/deploy.sh")
    assert "ghcr.io/${{ github.repository_owner }}/latexy-backend" in release
    for doc in _k8s_manifests():
        for container in _containers(doc):
            image = container["image"]
            if "latexy-backend" in image or "latexy-frontend" in image:
                if image.startswith("__LATEXY_"):
                    assert image in {"__LATEXY_BACKEND_IMAGE__", "__LATEXY_FRONTEND_IMAGE__"}
                else:
                    registry, separator, _path = image.partition("/")
                    assert separator and registry == "ghcr.io", image
    assert "render_deployment_manifests" in deploy_sh


def test_k8s_application_manifests_never_embed_mutable_latest_images():
    paths = (
        "k8s/backend/deployment.yaml",
        "k8s/frontend/deployment.yaml",
        "k8s/celery/celery-worker.yaml",
    )
    for path in paths:
        source = _read(path)
        assert ":latest" not in source, path
    assert "__LATEXY_BACKEND_IMAGE__" in _read("k8s/backend/deployment.yaml")
    assert "__LATEXY_FRONTEND_IMAGE__" in _read("k8s/frontend/deployment.yaml")


def test_k8s_migration_job_uses_exact_backend_image_and_required_settings():
    job = next(
        doc
        for doc in _load_all("k8s/database/migrations-job.yaml")
        if doc.get("kind") == "Job"
    )
    container = job["spec"]["template"]["spec"]["containers"][0]
    env = {entry["name"]: entry for entry in container["env"]}

    assert job["metadata"]["name"] == "latexy-migrations"
    assert job["spec"]["backoffLimit"] == 0
    assert container["image"] == "__LATEXY_BACKEND_IMAGE__"
    assert container["command"] == ["alembic", "upgrade", "head"]
    assert {"ENVIRONMENT", "DATABASE_URL", "BETTER_AUTH_SECRET", "JWT_SECRET_KEY", "API_KEY_ENCRYPTION_KEY"} <= set(env)
    assert env["DATABASE_URL"]["valueFrom"]["secretKeyRef"]["name"] == "latexy-secrets"


def test_k8s_deploy_validates_images_and_migrates_before_any_app_rollout():
    script = _read("k8s/deploy.sh")
    main = script.split("# Main execution", 1)[1]

    assert "validate_image_ref" in script
    assert "Mutable :latest application images are rejected." in script
    assert "kubectl delete job latexy-migrations" in script
    assert "kubectl wait --for=condition=complete job/latexy-migrations" in script
    assert "kubectl logs -n \"$NAMESPACE\" job/latexy-migrations" in script
    assert "kubectl exec -n \"$NAMESPACE\"" not in script
    assert "application rollout is aborted" in script
    assert "Backend component rollout is refused without the migration-gated full deploy" in script
    assert "Celery component rollout is refused without the migration-gated full deploy" in script
    assert script.count('resolve_image_refs') >= 3  # full deploy + refused backend/celery paths
    assert "awk -v backend=\"$BACKEND_IMAGE\"" in script
    assert "sed" not in script.split("render_manifest()", 1)[1].split("render_deployment_manifests", 1)[0]

    resolve = main.index("resolve_image_refs")
    render = main.index("render_deployment_manifests")
    database = main.index("deploy_database")
    redis = main.index("deploy_redis")
    migrations = main.index("run_migrations")
    backend = main.index("deploy_backend")
    frontend = main.index("deploy_frontend")
    celery = main.index("deploy_celery")
    assert resolve < render < database < redis < migrations < backend < frontend < celery


def test_k8s_image_validation_rejects_rendering_injection_and_mutable_refs():
    """Adversarial refs must fail before they reach manifest rendering."""
    script = _read("k8s/deploy.sh")
    function = script.split("validate_image_ref() {", 1)[1].split("\n}\n", 1)[0]
    command = """
validate_image_ref() {
%s
}
log() { :; }
for image in \
  'ghcr.io/sanskarpan/latexy-backend:latest' \
  'ghcr.io/sanskarpan/latexy-backend:v1.2.3|touch /tmp/pwned' \
  'ghcr.io/sanskarpan/latexy-backend:v1.2.3\\evil' \
  $'ghcr.io/sanskarpan/latexy-backend:v1.2.3\nINJECTED'; do
  if validate_image_ref BACKEND_IMAGE "$image"; then exit 1; fi
done
validate_image_ref BACKEND_IMAGE ghcr.io/sanskarpan/latexy-backend:v1.2.3
validate_image_ref BACKEND_IMAGE ghcr.io/sanskarpan/latexy-backend:sha-0123456789abcdef
validate_image_ref BACKEND_IMAGE ghcr.io/sanskarpan/latexy-backend@sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
""" % function
    result = subprocess.run(["bash", "-c", command], capture_output=True, text=True, check=False)
    assert result.returncode == 0, result.stderr


def test_release_instructions_migrate_exact_backend_before_compose_rollout():
    release = _read(".github/workflows/release.yml")
    migration = "docker compose -f docker-compose.prod.yml --env-file .env.production run --rm --no-deps backend alembic upgrade head"
    startup = "docker compose -f docker-compose.prod.yml --env-file .env.production up -d --no-build"

    assert migration in release
    assert startup in release
    assert "up -d --wait postgres redis minio tempo" in release
    assert "run --rm --no-deps minio-init" in release
    assert "docker compose -f docker-compose.prod.yml --env-file .env.production exec backend alembic upgrade head" not in release
    assert release.index("run --rm --no-deps backend alembic upgrade head") < release.index("up -d --no-build")


def test_legacy_deploy_migrates_built_backend_before_starting_app_processes():
    script = _read("scripts/deploy/deploy.sh")
    main = script.split("# Main deployment function", 1)[1]

    assert "docker-compose -f docker-compose.prod.yml build" in script
    assert "docker-compose -f docker-compose.prod.yml run --rm --no-deps backend alembic upgrade head" in script
    assert "docker-compose -f docker-compose.prod.yml up -d --no-build --remove-orphans" in script
    assert "exec -T backend alembic upgrade head" not in script
    assert "docker tag \"${IMAGE_PREFIX}/latexy-frontend:$version\" \"${IMAGE_PREFIX}/latexy-frontend:latest\"" not in script
    assert main.index("build_images") < main.index("run_migrations") < main.index("deploy_services")
    assert "LATEXY_VERSION=\"$version\"" in script
    assert "up -d --wait" in script
    assert "postgres redis minio tempo" in script
    assert "run --rm --no-deps minio-init" in script
    assert "--skip-build requires LATEXY_VERSION" in script
    assert "validate_image_version" in script


def test_legacy_deploy_version_resolution_rejects_dirty_and_normalizes_git_refs(tmp_path):
    """Build tags must be exact release tags or full clean commit SHAs."""
    script = _read("scripts/deploy/deploy.sh")
    function = script.split("get_current_version() {", 1)[1].split("\n}\n", 1)[0]
    wrapper = f'''\
log() {{ printf '%s\\n' "$*" >&2; }}
get_current_version() {{
{function}
}}
get_current_version
'''

    def git(*args: str) -> None:
        subprocess.run(["git", *args], cwd=tmp_path, check=True, capture_output=True)

    git("init", "-q")
    git("config", "user.email", "test@example.invalid")
    git("config", "user.name", "Deploy Test")
    (tmp_path / "tracked").write_text("one\n")
    git("add", "tracked")
    git("commit", "-qm", "initial")
    git("tag", "v1.2.3")

    exact = subprocess.run(["bash", "-c", wrapper], cwd=tmp_path, text=True, capture_output=True, check=True)
    assert exact.stdout.strip() == "v1.2.3"

    (tmp_path / "tracked").write_text("two\n")
    git("add", "tracked")
    git("commit", "-qm", "ahead")
    ahead = subprocess.run(["bash", "-c", wrapper], cwd=tmp_path, text=True, capture_output=True, check=True)
    assert ahead.stdout.strip() == f"sha-{subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=tmp_path, text=True).strip()}"

    (tmp_path / "tracked").write_text("dirty\n")
    dirty = subprocess.run(["bash", "-c", wrapper], cwd=tmp_path, text=True, capture_output=True, check=False)
    assert dirty.returncode != 0
