apiVersion: apps/v1
kind: Deployment
metadata:
  name: latexy-frontend
  namespace: latexy
  labels:
    app: latexy-frontend
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: latexy-frontend
  template:
    metadata:
      labels:
        app: latexy-frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: latexy-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: latexy-config
              key: api-url
        - name: NEXT_PUBLIC_WS_URL
          valueFrom:
            configMapKeyRef:
              name: latexy-config
              key: ws-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: latexy-frontend-service
  namespace: latexy
  labels:
    app: latexy-frontend
spec:
  selector:
    app: latexy-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
