"""Small bounded I/O helpers for untrusted response and generated-artifact data."""

from __future__ import annotations

import asyncio
import base64
import inspect
import zlib
from collections import deque
from collections.abc import Iterator
from pathlib import Path
from typing import Any, Mapping


class BoundedReadError(ValueError):
    """Raised when a bounded read would exceed its configured limit."""


# SyncTeX is generated output, but it is still consumed at worker/API trust
# boundaries. Keep enough room for large documents while bounding expansion.
MAX_SYNCTEX_COMPRESSED_BYTES = 8 * 1024 * 1024
MAX_SYNCTEX_DECOMPRESSED_BYTES = 32 * 1024 * 1024
MAX_COMPILED_PDF_BYTES = 20 * 1024 * 1024
# A recorder file is generated by the TeX engine, but its entries are still
# derived from the document and can be repeated without bound.  Keep enough
# room for a normal multi-file document while making the post-run inspection
# itself a bounded operation.
MAX_RECORDER_BYTES = 8 * 1024 * 1024
MAX_COMPILE_LOG_BYTES = 256 * 1024
MAX_COMPILE_LOG_LINE_BYTES = 8 * 1024
_LOG_TRUNCATION_MARKER = "[compile log truncated; showing bounded tail]"


def declared_content_length(headers: Mapping[str, Any]) -> int | None:
    """Return a valid non-negative Content-Length, or ``None`` if absent/invalid."""
    value = headers.get("content-length")
    if value is None:
        value = headers.get("Content-Length")
    if value is None:
        return None
    try:
        length = int(value)
    except (TypeError, ValueError):
        return None
    return length if length >= 0 else None


def decode_base64_bounded(value: str | bytes, max_bytes: int) -> bytes:
    """Decode a base64 artifact only when its encoded and decoded sizes fit."""
    if max_bytes < 0:
        raise ValueError("max_bytes must be non-negative")
    encoded_length = len(value)
    max_encoded_length = ((max_bytes + 2) // 3) * 4
    if encoded_length > max_encoded_length:
        raise BoundedReadError("base64 artifact exceeds byte limit")
    try:
        decoded = base64.b64decode(value, validate=True)
    except (ValueError, TypeError, base64.binascii.Error) as exc:
        raise BoundedReadError("invalid base64 artifact") from exc
    if len(decoded) > max_bytes:
        raise BoundedReadError("base64 artifact exceeds byte limit")
    return decoded


def bound_log_line(line: str, max_bytes: int = MAX_COMPILE_LOG_LINE_BYTES) -> tuple[str, bool]:
    """Bound one emitted log line while retaining a visible truncation marker."""
    if max_bytes < 1:
        raise ValueError("max_bytes must be positive")
    if len(line) <= max_bytes:
        raw = line.encode("utf-8", errors="replace")
        if len(raw) <= max_bytes:
            return line, False
    marker = " … [line truncated]"
    marker_bytes = marker.encode("utf-8")
    prefix_budget = max(0, max_bytes - len(marker_bytes))
    prefix = line[:prefix_budget].encode("utf-8", errors="replace")[:prefix_budget]
    prefix = prefix.decode("utf-8", errors="ignore")
    return prefix + marker, True


class BoundedTranscript:
    """Retain a bounded tail of compiler output while draining every input line."""

    def __init__(
        self,
        *,
        max_bytes: int = MAX_COMPILE_LOG_BYTES,
        max_line_bytes: int = MAX_COMPILE_LOG_LINE_BYTES,
    ) -> None:
        if max_bytes < 1 or max_line_bytes < 1:
            raise ValueError("transcript limits must be positive")
        self.max_bytes = max_bytes
        self.max_line_bytes = max_line_bytes
        self._tail: deque[str] = deque()
        self._tail_bytes = 0
        self.truncated = False
        self.first_error: str | None = None

    def append(self, line: str) -> str:
        bounded, _ = bound_log_line(line, self.max_line_bytes)
        if self.first_error is None:
            lowered = bounded.lower()
            if bounded.startswith("!") or "error" in lowered or "fatal" in lowered:
                self.first_error = bounded
        chunk_bytes = len(bounded.encode("utf-8")) + (1 if self._tail else 0)
        self._tail.append(bounded)
        self._tail_bytes += chunk_bytes
        while self._tail and self._tail_bytes > self.max_bytes:
            removed = self._tail.popleft()
            self._tail_bytes -= len(removed.encode("utf-8")) + (1 if self._tail else 0)
            self.truncated = True
        return bounded

    def text(self) -> str:
        tail = "\n".join(self._tail)
        prefix: list[str] = []
        if self.truncated:
            prefix.append(_LOG_TRUNCATION_MARKER)
        if self.first_error and self.first_error not in self._tail:
            prefix.append(f"First error: {self.first_error}")
        if prefix:
            tail = "\n".join(prefix + ([tail] if tail else []))
        encoded = tail.encode("utf-8", errors="replace")
        if len(encoded) <= self.max_bytes:
            return tail
        if prefix:
            marker = "\n".join(prefix) + "\n"
            marker_bytes = marker.encode("utf-8")
            if len(marker_bytes) >= self.max_bytes:
                return marker_bytes[: self.max_bytes].decode("utf-8", errors="ignore")
            tail_budget = self.max_bytes - len(marker_bytes)
            tail_bytes = "\n".join(self._tail).encode("utf-8", errors="replace")
            return marker + tail_bytes[-tail_budget:].decode("utf-8", errors="ignore")
        return encoded[-self.max_bytes :].decode("utf-8", errors="ignore")


def iter_bounded_lines(stream: Any, max_bytes: int = MAX_COMPILE_LOG_LINE_BYTES) -> Iterator[str]:
    """Drain a text/binary stream in bounded chunks and yield capped logical lines."""
    if max_bytes < 1:
        raise ValueError("max_bytes must be positive")
    read = getattr(stream, "read", None)
    if not callable(read):
        # Iteration obtains a complete logical line before this helper can
        # inspect it, so accepting an iterable here would only appear bounded.
        # Every production pipe/file caller supports read(size); fail before
        # consuming unsupported adapters.
        raise BoundedReadError("stream does not support bounded reads")

    pending = ""
    while True:
        raw_chunk = read(max_bytes)
        if not raw_chunk:
            break
        chunk = raw_chunk.decode("utf-8", errors="replace") if isinstance(raw_chunk, bytes) else str(raw_chunk)
        for part in chunk.splitlines(keepends=True):
            has_newline = part.endswith(("\n", "\r"))
            piece = part.rstrip("\r\n") if has_newline else part
            pending += piece
            if has_newline:
                yield bound_log_line(pending, max_bytes)[0]
                pending = ""
            elif len(pending.encode("utf-8", errors="replace")) >= max_bytes:
                yield bound_log_line(pending, max_bytes)[0]
                pending = ""
    if pending:
        yield bound_log_line(pending, max_bytes)[0]


async def capture_process_output_bounded(
    process: Any,
    max_bytes: int = MAX_COMPILE_LOG_BYTES,
) -> str:
    """Drain both subprocess pipes while retaining only a bounded transcript.

    Reading stdout and stderr concurrently prevents a compiler from blocking on
    a full pipe.  Each read is capped at the per-line limit, and the shared
    transcript enforces the aggregate limit.  Processes without bounded pipe
    readers are rejected rather than falling back to unbounded ``communicate()``.
    """
    if max_bytes < 1:
        raise ValueError("max_bytes must be positive")
    transcript = BoundedTranscript(max_bytes=max_bytes)

    async def drain(reader: Any) -> None:
        read = getattr(reader, "read", None)
        if not callable(read) or not inspect.iscoroutinefunction(read):
            return
        pending = ""
        while True:
            raw_chunk = await read(MAX_COMPILE_LOG_LINE_BYTES)
            if not raw_chunk:
                break
            chunk = raw_chunk.decode("utf-8", errors="replace") if isinstance(raw_chunk, bytes) else str(raw_chunk)
            for part in chunk.splitlines(keepends=True):
                has_newline = part.endswith(("\n", "\r"))
                piece = part.rstrip("\r\n") if has_newline else part
                pending += piece
                if has_newline or len(pending.encode("utf-8", errors="replace")) >= MAX_COMPILE_LOG_LINE_BYTES:
                    transcript.append(pending)
                    pending = ""
        if pending:
            transcript.append(pending)

    stdout = getattr(process, "stdout", None)
    stderr = getattr(process, "stderr", None)
    readers = [reader for reader in (stdout, stderr) if reader is not None]
    bounded_readers = [reader for reader in readers if inspect.iscoroutinefunction(getattr(reader, "read", None))]
    if not bounded_readers or len(bounded_readers) != len(readers):
        raise BoundedReadError("subprocess pipes do not support bounded reads")
    await asyncio.gather(*(drain(reader) for reader in bounded_readers))
    await process.wait()
    return transcript.text()


def read_text_file_bounded(path: Path, max_bytes: int = MAX_COMPILE_LOG_BYTES) -> str:
    """Read a text log through bounded binary chunks and retain its tail."""
    transcript = BoundedTranscript(max_bytes=max_bytes)
    with path.open("rb") as stream:
        for line in iter_bounded_lines(stream):
            transcript.append(line)
    return transcript.text()


async def read_httpx_response_bounded(response: Any, max_bytes: int) -> bytes:
    """Read decoded HTTP response bytes without crossing ``max_bytes``.

    ``httpx`` decodes content encodings before ``aiter_bytes`` yields chunks, so
    the limit applies to the bytes that the caller will retain in memory. The
    iterator chunk size is capped at ``max_bytes + 1`` as an additional guard
    for transports that ignore the requested size.
    """
    if max_bytes < 0:
        raise ValueError("max_bytes must be non-negative")
    declared = declared_content_length(getattr(response, "headers", {}))
    if declared is not None and declared > max_bytes:
        raise BoundedReadError("response exceeds byte limit")

    body = bytearray()
    async for chunk in response.aiter_bytes(chunk_size=max(1, max_bytes + 1)):
        if len(body) + len(chunk) > max_bytes:
            raise BoundedReadError("response exceeds byte limit")
        body.extend(chunk)
    return bytes(body)


def read_file_bounded(path: Path, max_bytes: int) -> bytes:
    """Read a regular file only when its size is at most ``max_bytes``."""
    if max_bytes < 0:
        raise ValueError("max_bytes must be non-negative")
    try:
        if path.stat().st_size > max_bytes:
            raise BoundedReadError("file exceeds byte limit")
    except OSError:
        raise
    with path.open("rb") as handle:
        data = handle.read(max_bytes + 1)
    if len(data) > max_bytes:
        raise BoundedReadError("file exceeds byte limit")
    return data


def read_gzip_file_bounded(
    path: Path,
    *,
    max_compressed_bytes: int,
    max_decompressed_bytes: int,
) -> bytes:
    """Incrementally decode a gzip file with compressed and output ceilings."""
    if max_compressed_bytes < 0 or max_decompressed_bytes < 0:
        raise ValueError("gzip limits must be non-negative")
    try:
        if path.stat().st_size > max_compressed_bytes:
            raise BoundedReadError("gzip input exceeds byte limit")
    except OSError:
        raise

    decoder = zlib.decompressobj(16 + zlib.MAX_WBITS)
    output = bytearray()
    compressed = 0
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(min(64 * 1024, max_compressed_bytes - compressed + 1))
            if not chunk:
                break
            compressed += len(chunk)
            if compressed > max_compressed_bytes:
                raise BoundedReadError("gzip input exceeds byte limit")
            decoded = decoder.decompress(chunk, max_decompressed_bytes - len(output) + 1)
            output.extend(decoded)
            if len(output) > max_decompressed_bytes or decoder.unconsumed_tail:
                raise BoundedReadError("gzip output exceeds byte limit")

    decoded = decoder.flush(max_decompressed_bytes - len(output) + 1)
    output.extend(decoded)
    if len(output) > max_decompressed_bytes or not decoder.eof:
        raise BoundedReadError("gzip output exceeds byte limit")
    return bytes(output)
