import { consumeDevEmailPreview, isDevPreviewRuntime } from '@/lib/email'

function isLoopbackHostname(hostname: string): boolean {
  const normalized = hostname.toLowerCase().replace(/^\[|\]$/g, '')
  return normalized === 'localhost' || normalized === '127.0.0.1' || normalized === '::1'
}

/**
 * Local-only email preview. Action links are intentionally available only to
 * a same-origin browser request in development, and each preview is consumed
 * once from process memory. This keeps local reset/verification testing useful
 * without ever placing tokens in server logs, URLs generated by the app, or
 * persistent storage.
 */
export function GET(request: Request): Response {
  if (!isDevPreviewRuntime()) {
    return Response.json({ message: 'Not found' }, { status: 404 })
  }

  const requestUrl = new URL(request.url)
  // Same-origin is not sufficient for a local-only endpoint: a DNS-rebinding
  // host (or a staging/public hostname with NODE_ENV mis-set) could otherwise
  // make the reset token available to any browser that can reach the process.
  // Keep this endpoint bound to exact loopback hostnames.
  if (!isLoopbackHostname(requestUrl.hostname)) {
    return Response.json({ message: 'Loopback access required.' }, { status: 404 })
  }

  const requestOrigin = requestUrl.origin
  const origin = request.headers.get('origin')
  const referer = request.headers.get('referer')
  let sameOrigin = origin === requestOrigin
  if (!sameOrigin && referer) {
    try { sameOrigin = new URL(referer).origin === requestOrigin } catch { sameOrigin = false }
  }
  if (!sameOrigin) return Response.json({ message: 'Same-origin access required.' }, { status: 403 })

  const preview = consumeDevEmailPreview()
  if (!preview) return Response.json({ message: 'No pending email preview.' }, { status: 404 })
  return Response.json(preview, {
    headers: {
      'Cache-Control': 'no-store, max-age=0',
      'Referrer-Policy': 'no-referrer',
      'X-Robots-Tag': 'noindex, nofollow, noarchive',
    },
  })
}
