export type SymbolCategory =
  | 'greek'
  | 'operators'
  | 'arrows'
  | 'relations'
  | 'set_notation'
  | 'misc'
  | 'accents'
  | 'delimiters'

export interface LaTeXSymbol {
  unicode: string
  command: string
  name: string
  package?: string
  category: SymbolCategory
}

export const SYMBOL_CATEGORIES: { id: SymbolCategory; label: string }[] = [
  { id: 'greek', label: 'Greek' },
  { id: 'operators', label: 'Operators' },
  { id: 'arrows', label: 'Arrows' },
  { id: 'relations', label: 'Relations' },
  { id: 'set_notation', label: 'Sets' },
  { id: 'delimiters', label: 'Delimiters' },
  { id: 'accents', label: 'Accents' },
  { id: 'misc', label: 'Misc' },
]

export const LATEX_SYMBOLS: LaTeXSymbol[] = [
  // ── Greek lowercase ─────────────────────────────────────────────────────
  { unicode: 'α', command: '\\alpha', name: 'alpha', category: 'greek' },
  { unicode: 'β', command: '\\beta', name: 'beta', category: 'greek' },
  { unicode: 'γ', command: '\\gamma', name: 'gamma', category: 'greek' },
  { unicode: 'δ', command: '\\delta', name: 'delta', category: 'greek' },
  { unicode: 'ε', command: '\\epsilon', name: 'epsilon', category: 'greek' },
  { unicode: 'ε', command: '\\varepsilon', name: 'varepsilon', category: 'greek' },
  { unicode: 'ζ', command: '\\zeta', name: 'zeta', category: 'greek' },
  { unicode: 'η', command: '\\eta', name: 'eta', category: 'greek' },
  { unicode: 'θ', command: '\\theta', name: 'theta', category: 'greek' },
  { unicode: 'ϑ', command: '\\vartheta', name: 'vartheta', category: 'greek' },
  { unicode: 'ι', command: '\\iota', name: 'iota', category: 'greek' },
  { unicode: 'κ', command: '\\kappa', name: 'kappa', category: 'greek' },
  { unicode: 'λ', command: '\\lambda', name: 'lambda', category: 'greek' },
  { unicode: 'μ', command: '\\mu', name: 'mu', category: 'greek' },
  { unicode: 'ν', command: '\\nu', name: 'nu', category: 'greek' },
  { unicode: 'ξ', command: '\\xi', name: 'xi', category: 'greek' },
  { unicode: 'π', command: '\\pi', name: 'pi', category: 'greek' },
  { unicode: 'ϖ', command: '\\varpi', name: 'varpi', category: 'greek' },
  { unicode: 'ρ', command: '\\rho', name: 'rho', category: 'greek' },
  { unicode: 'ϱ', command: '\\varrho', name: 'varrho', category: 'greek' },
  { unicode: 'σ', command: '\\sigma', name: 'sigma', category: 'greek' },
  { unicode: 'ς', command: '\\varsigma', name: 'varsigma', category: 'greek' },
  { unicode: 'τ', command: '\\tau', name: 'tau', category: 'greek' },
  { unicode: 'υ', command: '\\upsilon', name: 'upsilon', category: 'greek' },
  { unicode: 'φ', command: '\\phi', name: 'phi', category: 'greek' },
  { unicode: 'ϕ', command: '\\varphi', name: 'varphi', category: 'greek' },
  { unicode: 'χ', command: '\\chi', name: 'chi', category: 'greek' },
  { unicode: 'ψ', command: '\\psi', name: 'psi', category: 'greek' },
  { unicode: 'ω', command: '\\omega', name: 'omega', category: 'greek' },

  // ── Greek uppercase ─────────────────────────────────────────────────────
  { unicode: 'Γ', command: '\\Gamma', name: 'Gamma uppercase', category: 'greek' },
  { unicode: 'Δ', command: '\\Delta', name: 'Delta uppercase', category: 'greek' },
  { unicode: 'Θ', command: '\\Theta', name: 'Theta uppercase', category: 'greek' },
  { unicode: 'Λ', command: '\\Lambda', name: 'Lambda uppercase', category: 'greek' },
  { unicode: 'Ξ', command: '\\Xi', name: 'Xi uppercase', category: 'greek' },
  { unicode: 'Π', command: '\\Pi', name: 'Pi uppercase', category: 'greek' },
  { unicode: 'Σ', command: '\\Sigma', name: 'Sigma uppercase', category: 'greek' },
  { unicode: 'Υ', command: '\\Upsilon', name: 'Upsilon uppercase', category: 'greek' },
  { unicode: 'Φ', command: '\\Phi', name: 'Phi uppercase', category: 'greek' },
  { unicode: 'Ψ', command: '\\Psi', name: 'Psi uppercase', category: 'greek' },
  { unicode: 'Ω', command: '\\Omega', name: 'Omega uppercase', category: 'greek' },

  // ── Operators ───────────────────────────────────────────────────────────
  { unicode: '±', command: '\\pm', name: 'plus minus', category: 'operators' },
  { unicode: '∓', command: '\\mp', name: 'minus plus', category: 'operators' },
  { unicode: '×', command: '\\times', name: 'times multiply', category: 'operators' },
  { unicode: '÷', command: '\\div', name: 'divide division', category: 'operators' },
  { unicode: '·', command: '\\cdot', name: 'center dot', category: 'operators' },
  { unicode: '∗', command: '\\ast', name: 'asterisk', category: 'operators' },
  { unicode: '⋆', command: '\\star', name: 'star', category: 'operators' },
  { unicode: '†', command: '\\dagger', name: 'dagger', category: 'operators' },
  { unicode: '‡', command: '\\ddagger', name: 'double dagger', category: 'operators' },
  { unicode: '∘', command: '\\circ', name: 'circle composition', category: 'operators' },
  { unicode: '•', command: '\\bullet', name: 'bullet', category: 'operators' },
  { unicode: '∫', command: '\\int', name: 'integral', category: 'operators' },
  { unicode: '∬', command: '\\iint', name: 'double integral', category: 'operators', package: 'amsmath' },
  { unicode: '∭', command: '\\iiint', name: 'triple integral', category: 'operators', package: 'amsmath' },
  { unicode: '∮', command: '\\oint', name: 'contour integral', category: 'operators' },
  { unicode: '∑', command: '\\sum', name: 'sum summation', category: 'operators' },
  { unicode: '∏', command: '\\prod', name: 'product', category: 'operators' },
  { unicode: '∐', command: '\\coprod', name: 'coproduct', category: 'operators' },
  { unicode: '⋃', command: '\\bigcup', name: 'big union', category: 'operators' },
  { unicode: '⋂', command: '\\bigcap', name: 'big intersection', category: 'operators' },
  { unicode: '⊕', command: '\\oplus', name: 'direct sum circle plus', category: 'operators' },
  { unicode: '⊗', command: '\\otimes', name: 'tensor product circle times', category: 'operators' },
  { unicode: '⊖', command: '\\ominus', name: 'circle minus', category: 'operators' },
  { unicode: '√', command: '\\sqrt{}', name: 'square root', category: 'operators' },
  { unicode: '∂', command: '\\partial', name: 'partial derivative', category: 'operators' },
  { unicode: '∇', command: '\\nabla', name: 'nabla gradient del', category: 'operators' },
  { unicode: '∧', command: '\\wedge', name: 'wedge logical and', category: 'operators' },
  { unicode: '∨', command: '\\vee', name: 'vee logical or', category: 'operators' },
  { unicode: '¬', command: '\\neg', name: 'negation not', category: 'operators' },
  { unicode: 'ℜ', command: '\\Re', name: 'real part', category: 'operators' },
  { unicode: 'ℑ', command: '\\Im', name: 'imaginary part', category: 'operators' },

  // ── Arrows ──────────────────────────────────────────────────────────────
  { unicode: '←', command: '\\leftarrow', name: 'left arrow', category: 'arrows' },
  { unicode: '→', command: '\\rightarrow', name: 'right arrow', category: 'arrows' },
  { unicode: '↑', command: '\\uparrow', name: 'up arrow', category: 'arrows' },
  { unicode: '↓', command: '\\downarrow', name: 'down arrow', category: 'arrows' },
  { unicode: '↔', command: '\\leftrightarrow', name: 'left right arrow', category: 'arrows' },
  { unicode: '↕', command: '\\updownarrow', name: 'up down arrow', category: 'arrows' },
  { unicode: '⇐', command: '\\Leftarrow', name: 'double left arrow', category: 'arrows' },
  { unicode: '⇒', command: '\\Rightarrow', name: 'double right arrow implies', category: 'arrows' },
  { unicode: '⇑', command: '\\Uparrow', name: 'double up arrow', category: 'arrows' },
  { unicode: '⇓', command: '\\Downarrow', name: 'double down arrow', category: 'arrows' },
  { unicode: '⇔', command: '\\Leftrightarrow', name: 'double left right arrow iff', category: 'arrows' },
  { unicode: '⇕', command: '\\Updownarrow', name: 'double up down arrow', category: 'arrows' },
  { unicode: '↦', command: '\\mapsto', name: 'maps to', category: 'arrows' },
  { unicode: '↪', command: '\\hookrightarrow', name: 'hook right arrow', category: 'arrows' },
  { unicode: '↩', command: '\\hookleftarrow', name: 'hook left arrow', category: 'arrows' },
  { unicode: '⟶', command: '\\longrightarrow', name: 'long right arrow', category: 'arrows' },
  { unicode: '⟵', command: '\\longleftarrow', name: 'long left arrow', category: 'arrows' },
  { unicode: '⟹', command: '\\Longrightarrow', name: 'long double right arrow', category: 'arrows' },
  { unicode: '⟸', command: '\\Longleftarrow', name: 'long double left arrow', category: 'arrows' },
  { unicode: '⟺', command: '\\Longleftrightarrow', name: 'long double left right arrow', category: 'arrows' },
  { unicode: '↗', command: '\\nearrow', name: 'north east arrow', category: 'arrows' },
  { unicode: '↘', command: '\\searrow', name: 'south east arrow', category: 'arrows' },
  { unicode: '↙', command: '\\swarrow', name: 'south west arrow', category: 'arrows' },
  { unicode: '↖', command: '\\nwarrow', name: 'north west arrow', category: 'arrows' },
  { unicode: '⇀', command: '\\rightharpoonup', name: 'right harpoon up', category: 'arrows' },
  { unicode: '⇁', command: '\\rightharpoondown', name: 'right harpoon down', category: 'arrows' },

  // ── Relations ───────────────────────────────────────────────────────────
  { unicode: '≤', command: '\\leq', name: 'less than or equal', category: 'relations' },
  { unicode: '≥', command: '\\geq', name: 'greater than or equal', category: 'relations' },
  { unicode: '≠', command: '\\neq', name: 'not equal', category: 'relations' },
  { unicode: '≈', command: '\\approx', name: 'approximately', category: 'relations' },
  { unicode: '≡', command: '\\equiv', name: 'equivalent congruent', category: 'relations' },
  { unicode: '≅', command: '\\cong', name: 'congruent isomorphic', category: 'relations' },
  { unicode: '∼', command: '\\sim', name: 'similar tilde', category: 'relations' },
  { unicode: '≃', command: '\\simeq', name: 'similar or equal', category: 'relations' },
  { unicode: '≺', command: '\\prec', name: 'precedes', category: 'relations' },
  { unicode: '≻', command: '\\succ', name: 'succeeds', category: 'relations' },
  { unicode: '≼', command: '\\preceq', name: 'precedes or equal', category: 'relations', package: 'amssymb' },
  { unicode: '≽', command: '\\succeq', name: 'succeeds or equal', category: 'relations', package: 'amssymb' },
  { unicode: '≪', command: '\\ll', name: 'much less than', category: 'relations' },
  { unicode: '≫', command: '\\gg', name: 'much greater than', category: 'relations' },
  { unicode: '⊥', command: '\\perp', name: 'perpendicular', category: 'relations' },
  { unicode: '∥', command: '\\parallel', name: 'parallel', category: 'relations' },
  { unicode: '∝', command: '\\propto', name: 'proportional to', category: 'relations' },
  { unicode: '≐', command: '\\doteq', name: 'dot equal', category: 'relations' },
  { unicode: '⊢', command: '\\vdash', name: 'turnstile proves', category: 'relations' },
  { unicode: '⊣', command: '\\dashv', name: 'reverse turnstile', category: 'relations' },
  { unicode: '⊨', command: '\\models', name: 'models satisfies', category: 'relations' },
  { unicode: '≍', command: '\\asymp', name: 'asymptotically equal', category: 'relations' },
  { unicode: '⋈', command: '\\bowtie', name: 'bowtie join', category: 'relations' },

  // ── Set notation ────────────────────────────────────────────────────────
  { unicode: '∈', command: '\\in', name: 'element of member', category: 'set_notation' },
  { unicode: '∉', command: '\\notin', name: 'not element of', category: 'set_notation' },
  { unicode: '∋', command: '\\ni', name: 'contains member', category: 'set_notation' },
  { unicode: '⊂', command: '\\subset', name: 'subset', category: 'set_notation' },
  { unicode: '⊃', command: '\\supset', name: 'superset', category: 'set_notation' },
  { unicode: '⊆', command: '\\subseteq', name: 'subset or equal', category: 'set_notation' },
  { unicode: '⊇', command: '\\supseteq', name: 'superset or equal', category: 'set_notation' },
  { unicode: '⊄', command: '\\not\\subset', name: 'not subset', category: 'set_notation' },
  { unicode: '∪', command: '\\cup', name: 'union', category: 'set_notation' },
  { unicode: '∩', command: '\\cap', name: 'intersection', category: 'set_notation' },
  { unicode: '∅', command: '\\emptyset', name: 'empty set', category: 'set_notation' },
  { unicode: '∅', command: '\\varnothing', name: 'empty set variant', category: 'set_notation', package: 'amssymb' },
  { unicode: '∀', command: '\\forall', name: 'for all universal', category: 'set_notation' },
  { unicode: '∃', command: '\\exists', name: 'there exists existential', category: 'set_notation' },
  { unicode: '∄', command: '\\nexists', name: 'does not exist', category: 'set_notation', package: 'amssymb' },
  { unicode: 'ℕ', command: '\\mathbb{N}', name: 'natural numbers', category: 'set_notation', package: 'amssymb' },
  { unicode: 'ℤ', command: '\\mathbb{Z}', name: 'integers', category: 'set_notation', package: 'amssymb' },
  { unicode: 'ℚ', command: '\\mathbb{Q}', name: 'rationals', category: 'set_notation', package: 'amssymb' },
  { unicode: 'ℝ', command: '\\mathbb{R}', name: 'real numbers', category: 'set_notation', package: 'amssymb' },
  { unicode: 'ℂ', command: '\\mathbb{C}', name: 'complex numbers', category: 'set_notation', package: 'amssymb' },

  // ── Delimiters ──────────────────────────────────────────────────────────
  { unicode: '⟨', command: '\\langle', name: 'left angle bracket', category: 'delimiters' },
  { unicode: '⟩', command: '\\rangle', name: 'right angle bracket', category: 'delimiters' },
  { unicode: '⌈', command: '\\lceil', name: 'left ceiling', category: 'delimiters' },
  { unicode: '⌉', command: '\\rceil', name: 'right ceiling', category: 'delimiters' },
  { unicode: '⌊', command: '\\lfloor', name: 'left floor', category: 'delimiters' },
  { unicode: '⌋', command: '\\rfloor', name: 'right floor', category: 'delimiters' },
  { unicode: '‖', command: '\\|', name: 'double vertical bar norm', category: 'delimiters' },
  { unicode: '|', command: '\\mid', name: 'vertical bar divides', category: 'delimiters' },
  { unicode: '{', command: '\\{', name: 'left brace', category: 'delimiters' },
  { unicode: '}', command: '\\}', name: 'right brace', category: 'delimiters' },
  { unicode: '\\', command: '\\backslash', name: 'backslash', category: 'delimiters' },

  // ── Accents ─────────────────────────────────────────────────────────────
  { unicode: 'â', command: '\\hat{a}', name: 'hat accent', category: 'accents' },
  { unicode: 'ā', command: '\\bar{a}', name: 'bar overline accent', category: 'accents' },
  { unicode: 'ȧ', command: '\\dot{a}', name: 'dot accent', category: 'accents' },
  { unicode: 'ä', command: '\\ddot{a}', name: 'double dot umlaut', category: 'accents' },
  { unicode: 'ã', command: '\\tilde{a}', name: 'tilde accent', category: 'accents' },
  { unicode: 'ă', command: '\\breve{a}', name: 'breve accent', category: 'accents' },
  { unicode: 'ǎ', command: '\\check{a}', name: 'check caron accent', category: 'accents' },
  { unicode: 'a⃗', command: '\\vec{a}', name: 'vector arrow accent', category: 'accents' },
  { unicode: 'a̲', command: '\\underline{a}', name: 'underline', category: 'accents' },
  { unicode: 'a͡b', command: '\\widehat{ab}', name: 'wide hat', category: 'accents' },
  { unicode: 'ã̃b', command: '\\widetilde{ab}', name: 'wide tilde', category: 'accents' },
  { unicode: 'a̅', command: '\\overline{a}', name: 'overline', category: 'accents' },

  // ── Misc ────────────────────────────────────────────────────────────────
  { unicode: '∞', command: '\\infty', name: 'infinity', category: 'misc' },
  { unicode: '…', command: '\\ldots', name: 'horizontal dots ellipsis', category: 'misc' },
  { unicode: '⋯', command: '\\cdots', name: 'centered dots', category: 'misc' },
  { unicode: '⋮', command: '\\vdots', name: 'vertical dots', category: 'misc' },
  { unicode: '⋱', command: '\\ddots', name: 'diagonal dots', category: 'misc' },
  { unicode: 'ℓ', command: '\\ell', name: 'script l', category: 'misc' },
  { unicode: 'ℏ', command: '\\hbar', name: 'h bar planck', category: 'misc' },
  { unicode: '℘', command: '\\wp', name: 'weierstrass p', category: 'misc' },
  { unicode: '∠', command: '\\angle', name: 'angle', category: 'misc' },
  { unicode: '△', command: '\\triangle', name: 'triangle', category: 'misc' },
  { unicode: '□', command: '\\square', name: 'square box', category: 'misc', package: 'amssymb' },
  { unicode: '♦', command: '\\diamond', name: 'diamond', category: 'misc' },
  { unicode: '♣', command: '\\clubsuit', name: 'club suit', category: 'misc' },
  { unicode: '♠', command: '\\spadesuit', name: 'spade suit', category: 'misc' },
  { unicode: '♥', command: '\\heartsuit', name: 'heart suit', category: 'misc' },
  { unicode: '♦', command: '\\diamondsuit', name: 'diamond suit', category: 'misc' },
  { unicode: '°', command: '\\degree', name: 'degree', category: 'misc', package: 'gensymb' },
  { unicode: 'ℵ', command: '\\aleph', name: 'aleph', category: 'misc' },
  { unicode: '†', command: '\\dag', name: 'dagger text', category: 'misc' },
  { unicode: '§', command: '\\S', name: 'section sign', category: 'misc' },
  { unicode: '©', command: '\\copyright', name: 'copyright', category: 'misc' },
  { unicode: '£', command: '\\pounds', name: 'pound sterling', category: 'misc' },
  { unicode: '✓', command: '\\checkmark', name: 'checkmark tick', category: 'misc', package: 'amssymb' },
]
